server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

spring:
  config:
    import: optional:configserver:http://root:secret@localhost:9000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_service_database
    driverClassName: org.postgresql.Driver
    username: authorization_service
    password: secret
    hikari:
      connectionTimeout: 10000  # 10 seconds
      maximumPoolSize: 10
      minimumIdle: 1           # min connections that are held
      idleTimeout: 300000       # 05 minutes
  data.web:
    pageable:
      default-page-size: 10
  devtools:
    add-properties: false

authentication-service:
  bootstrap:
    authorizationServer: true
    client: true
  login-enabled: true
  default:
    technical-user: Technical User
  loadPageSize: 1000