server:
  port: 8761

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"



spring:
  application:
    name: discovery-service

  redis:
    host: localhost
    port: 6379

  config:
    import: optional:configserver:http://root:secret@localhost:8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

